### ISSUE TITLE
Removing items doesn't work for items not on the current page

### ISSUE THREAD

**Issue by mskazy** [zachpainter77/DatatablesForEach-Custom-Knockout-Binding#1]
When you do something like a removeAll on the observableArray only the DOM elements related to the array items on the active page get removed.  This gives an incorrect result where the post condition should be an empty table and instead DOM elements from the next page are displayed:

https://jsfiddle.net/wv3rjygy/6/

Thanks!

**Comment by zachpainter77** [comment]
Ahh..  yes! The paging with jquery datables is hard to integrate with knockout... I will work on this, however in the meantime I would suggest not using paging.  I would use scrolling if necessary.

**Comment by zachpainter77** [comment]
Ok I fixed the issue with the binding... The key here was to call DataTables().clear() before calling DataTables().destroy()

I updated the external reference in your fiddle to use the latest version of the binding so you can see that it is working now. Good eye! thanks for the heads up!

https://jsfiddle.net/wv3rjygy/7/

**Comment by zachpainter77** [comment]
@mskazy The fixed that I proposed did not work... It broke the datables somehow... however I got your scenario to work by calling the clear function before removing all of the items....

``` javascript

this.removeAll = function() {
            $('#example').DataTable().clear();
             this.people.removeAll();
};

```

**Comment by zachpainter77** [comment]
@mskazy I updated the binding... This fixes the remove all issue. Thanks again.
