### ISSUE TITLE
Sort Order

### ISSUE THREAD

**Issue by redowl3** [zachpainter77/DatatablesForEach-Custom-Knockout-Binding#7]
Hi,
Loving the binding it's saved me a ton of time but how do I set the sort order to be desc or asc for a particular column?

Grateful for any help

**Comment by zachpainter77** [comment]
I'm pretty sure you could do this with the datatables initialization object

**Comment by jammy-git** [comment]
Is it possible to get the Knockout field that is bound to the sorted column?

Or bind the sort order column field to a ko.observable?
